///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace QQ
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BasigBugMaxInt recording.
    /// </summary>
    [TestModule("949b239b-cc25-4e63-9f82-c9e71c0d8612", ModuleType.Recording, 1)]
    public partial class BasigBugMaxInt : ITestModule
    {
        /// <summary>
        /// Holds an instance of the QQRepository repository.
        /// </summary>
        public static QQRepository repo = QQRepository.Instance;

        static BasigBugMaxInt instance = new BasigBugMaxInt();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BasigBugMaxInt()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BasigBugMaxInt Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.Next' at 26;9.", repo.NewProtocolWizard.NextInfo, new RecordItemIndex(0));
            repo.NewProtocolWizard.Next.Click("26;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.Next' at 26;9.", repo.NewProtocolWizard.NextInfo, new RecordItemIndex(1));
            repo.NewProtocolWizard.Next.Click("26;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.ListItem1x11' at 62;17.", repo.NewProtocolWizard.ListItem1x11Info, new RecordItemIndex(2));
            repo.NewProtocolWizard.ListItem1x11.Click("62;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.Next' at 44;10.", repo.NewProtocolWizard.NextInfo, new RecordItemIndex(3));
            repo.NewProtocolWizard.Next.Click("44;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.Next' at 22;17.", repo.NewProtocolWizard.NextInfo, new RecordItemIndex(4));
            repo.NewProtocolWizard.Next.Click("22;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeListItem2' at 11;11.", repo.NewProtocolWizard.SomeListItem2Info, new RecordItemIndex(5));
            repo.NewProtocolWizard.SomeListItem2.Click("11;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.Next' at 30;10.", repo.NewProtocolWizard.NextInfo, new RecordItemIndex(6));
            repo.NewProtocolWizard.Next.Click("30;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'NewProtocolWizard.TabPagePad.SomeText' at 134;20.", repo.NewProtocolWizard.TabPagePad.SomeTextInfo, new RecordItemIndex(7));
            repo.NewProtocolWizard.TabPagePad.SomeText.MoveTo("134;20");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(8));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}'.", new RecordItemIndex(9));
            Keyboard.Press("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '9999999999999999999999999999'.", new RecordItemIndex(10));
            Keyboard.Press("9999999999999999999999999999");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '9'.", new RecordItemIndex(11));
            Keyboard.Press("9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking Focus() on item 'NewProtocolWizard'.", repo.NewProtocolWizard.SelfInfo, new RecordItemIndex(12));
            repo.NewProtocolWizard.Self.Focus();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(13));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'NewProtocolWizard.Next' at 30;10.", repo.NewProtocolWizard.NextInfo, new RecordItemIndex(14));
            repo.NewProtocolWizard.Next.DoubleClick("30;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(15));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.Back' at 22;5.", repo.NewProtocolWizard.BackInfo, new RecordItemIndex(16));
            repo.NewProtocolWizard.Back.Click("22;5");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
