///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace QQ
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BasicCreating recording.
    /// </summary>
    [TestModule("c7c6c0ae-ebe9-4aba-b50e-83eebaac9310", ModuleType.Recording, 1)]
    public partial class BasicCreating : ITestModule
    {
        /// <summary>
        /// Holds an instance of the QQRepository repository.
        /// </summary>
        public static QQRepository repo = QQRepository.Instance;

        static BasicCreating instance = new BasicCreating();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BasicCreating()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BasicCreating Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.Next' at 26;8.", repo.NewProtocolWizard.NextInfo, new RecordItemIndex(0));
            repo.NewProtocolWizard.Next.Click("26;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.Next' at 26;8.", repo.NewProtocolWizard.NextInfo, new RecordItemIndex(1));
            repo.NewProtocolWizard.Next.Click("26;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.Next' at 26;8.", repo.NewProtocolWizard.NextInfo, new RecordItemIndex(2));
            repo.NewProtocolWizard.Next.Click("26;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.Next' at 26;8.", repo.NewProtocolWizard.NextInfo, new RecordItemIndex(3));
            repo.NewProtocolWizard.Next.Click("26;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.Next' at 59;14.", repo.NewProtocolWizard.NextInfo, new RecordItemIndex(4));
            repo.NewProtocolWizard.Next.Click("59;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.SomeListItem2' at 11;11.", repo.NewProtocolWizard.SomeListItem2Info, new RecordItemIndex(5));
            repo.NewProtocolWizard.SomeListItem2.Click("11;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.Next' at 57;11.", repo.NewProtocolWizard.NextInfo, new RecordItemIndex(6));
            repo.NewProtocolWizard.Next.Click("57;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.Next' at 47;7.", repo.NewProtocolWizard.NextInfo, new RecordItemIndex(7));
            repo.NewProtocolWizard.Next.Click("47;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.Next' at 47;7.", repo.NewProtocolWizard.NextInfo, new RecordItemIndex(8));
            repo.NewProtocolWizard.Next.Click("47;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.Finish' at 47;7.", repo.NewProtocolWizard.FinishInfo, new RecordItemIndex(9));
            repo.NewProtocolWizard.Finish.Click("47;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolMyEndpoint12x8Protocol2.Ribbon.SomeTabPage' at 52;49.", repo.ProtocolMyEndpoint12x8Protocol2.Ribbon.SomeTabPageInfo, new RecordItemIndex(10));
            repo.ProtocolMyEndpoint12x8Protocol2.Ribbon.SomeTabPage.Click("52;49");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolMyEndpoint12x8Protocol2.File' at 30;15.", repo.ProtocolMyEndpoint12x8Protocol2.FileInfo, new RecordItemIndex(11));
            repo.ProtocolMyEndpoint12x8Protocol2.File.Click("30;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolMyEndpoint12x8Protocol2.ControlLabel' at 14;8.", repo.ProtocolMyEndpoint12x8Protocol2.ControlLabelInfo, new RecordItemIndex(12));
            repo.ProtocolMyEndpoint12x8Protocol2.ControlLabel.Click("14;8");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
