///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace QQ
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckWithoutAnyLayer recording.
    /// </summary>
    [TestModule("a5c116d2-836c-412d-a88f-759d48581590", ModuleType.Recording, 1)]
    public partial class CheckWithoutAnyLayer : ITestModule
    {
        /// <summary>
        /// Holds an instance of the QQRepository repository.
        /// </summary>
        public static QQRepository repo = QQRepository.Instance;

        static CheckWithoutAnyLayer instance = new CheckWithoutAnyLayer();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckWithoutAnyLayer()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckWithoutAnyLayer Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.EditButton' at 72;13.", repo.NewProtocolWizard.EditButtonInfo, new RecordItemIndex(0));
            repo.NewProtocolWizard.EditButton.Click("72;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.Clear' at 14;2.", repo.LayoutEditor.ClearInfo, new RecordItemIndex(1));
            repo.LayoutEditor.Clear.Click("14;2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='False') on item 'LayoutEditor.ElementSaveButton'.", repo.LayoutEditor.ElementSaveButtonInfo, new RecordItemIndex(2));
            Validate.Attribute(repo.LayoutEditor.ElementSaveButtonInfo, "Enabled", "False");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor' at 1099;787.", repo.LayoutEditor.SelfInfo, new RecordItemIndex(3));
            repo.LayoutEditor.Self.Click("1099;787");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LayoutEditor.ElementSaveButton' at 35;24.", repo.LayoutEditor.ElementSaveButtonInfo, new RecordItemIndex(4));
            repo.LayoutEditor.ElementSaveButton.Click("35;24");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
