///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace QQ
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckOtherWithoutMeasurements recording.
    /// </summary>
    [TestModule("359fb8f1-5393-42d5-9296-5b9d14b40a9c", ModuleType.Recording, 1)]
    public partial class CheckOtherWithoutMeasurements : ITestModule
    {
        /// <summary>
        /// Holds an instance of the QQRepository repository.
        /// </summary>
        public static QQRepository repo = QQRepository.Instance;

        static CheckOtherWithoutMeasurements instance = new CheckOtherWithoutMeasurements();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckOtherWithoutMeasurements()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckOtherWithoutMeasurements Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.Next' at 47;17.", repo.NewProtocolWizard.NextInfo, new RecordItemIndex(0));
            repo.NewProtocolWizard.Next.Click("47;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.GoogleChrome.OtherCombination' at 169;15.", repo.NewProtocolWizard.GoogleChrome.OtherCombinationInfo, new RecordItemIndex(1));
            repo.NewProtocolWizard.GoogleChrome.OtherCombination.Click("169;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.Next' at 24;12.", repo.NewProtocolWizard.NextInfo, new RecordItemIndex(2));
            repo.NewProtocolWizard.Next.Click("24;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='False') on item 'NewProtocolWizard.Next'.", repo.NewProtocolWizard.NextInfo, new RecordItemIndex(3));
            Validate.Attribute(repo.NewProtocolWizard.NextInfo, "Enabled", "False");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.Back1' at 63;12.", repo.NewProtocolWizard.Back1Info, new RecordItemIndex(4));
            repo.NewProtocolWizard.Back1.Click("63;12");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
