///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace QQ
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckWithoutAnySamples recording.
    /// </summary>
    [TestModule("db31ddad-59cd-4cca-bee6-6d86f72eabcd", ModuleType.Recording, 1)]
    public partial class CheckWithoutAnySamples : ITestModule
    {
        /// <summary>
        /// Holds an instance of the QQRepository repository.
        /// </summary>
        public static QQRepository repo = QQRepository.Instance;

        static CheckWithoutAnySamples instance = new CheckWithoutAnySamples();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckWithoutAnySamples()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckWithoutAnySamples Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Checked to 'False' on item 'NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBox'.", repo.NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBoxInfo, new RecordItemIndex(0));
            repo.NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBox.Element.SetAttributeValue("Checked", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Checked to 'False' on item 'NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBox1'.", repo.NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBox1Info, new RecordItemIndex(1));
            repo.NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBox1.Element.SetAttributeValue("Checked", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Checked to 'False' on item 'NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBox2'.", repo.NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBox2Info, new RecordItemIndex(2));
            repo.NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBox2.Element.SetAttributeValue("Checked", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Checked to 'False' on item 'NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBox3'.", repo.NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBox3Info, new RecordItemIndex(3));
            repo.NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBox3.Element.SetAttributeValue("Checked", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Checked to 'False' on item 'NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBox4'.", repo.NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBox4Info, new RecordItemIndex(4));
            repo.NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBox4.Element.SetAttributeValue("Checked", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Checked to 'False' on item 'NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBox5'.", repo.NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBox5Info, new RecordItemIndex(5));
            repo.NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBox5.Element.SetAttributeValue("Checked", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Checked to 'False' on item 'NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBox6'.", repo.NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBox6Info, new RecordItemIndex(6));
            repo.NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBox6.Element.SetAttributeValue("Checked", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Checked to 'False' on item 'NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBox7'.", repo.NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBox7Info, new RecordItemIndex(7));
            repo.NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBox7.Element.SetAttributeValue("Checked", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Checked to 'False' on item 'NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBox8'.", repo.NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBox8Info, new RecordItemIndex(8));
            repo.NewProtocolWizard.SampleTypesSimplifiedView.SomeCheckBox8.Element.SetAttributeValue("Checked", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.Next' at 27;14.", repo.NewProtocolWizard.NextInfo, new RecordItemIndex(9));
            repo.NewProtocolWizard.Next.Click("27;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'NewProtocolWizard.NewProtocolWizard'.", repo.NewProtocolWizard.NewProtocolWizardInfo, new RecordItemIndex(10));
            Validate.Exists(repo.NewProtocolWizard.NewProtocolWizardInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Escape}'.", new RecordItemIndex(11));
            Keyboard.Press("{Escape}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
