///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace QQ
{
	public partial class CheckAddingSampleType_byCode
	{
		/// <summary>
		/// This method gets called right after the recording has been started.
		/// It can be used to execute recording specific initialization code.
		/// </summary>
		private void Init()
		{
			// Your recording specific initialization code goes here.
		}

		public void UserCodeMethod(RepoItemInfo textInfo, RepoItemInfo buttonInfo, RepoItemInfo textInfo1, RepoItemInfo buttonInfo1, RepoItemInfo listitemInfo, RepoItemInfo buttonInfo2, RepoItemInfo buttonInfo3)
		{
			//         	 Open Type Manager
			textInfo.FindAdapter<Text>().Click("1;1");
			
			// Click Add Sample
			buttonInfo.FindAdapter<Button>().Click("1;1");
			
			// Change text to Test
			textInfo1.FindAdapter<Text>().Element.SetAttributeValue("Text", "Test");
			
			// Change sample type
			buttonInfo1.FindAdapter<Button>().Click("1;1");
			
			//listitemInfo.FindAdapter<ListItem>().Click("1;1");
			
			//buttonInfo1.FindAdapter<Button>().
			listitemInfo.FindAdapter<ListItem>().Selected = true;
				//.Select("Unknown");
				
				//Element.SetAttributeValue("Text", "Unknown");
				
				//SetAttributeValue("", "Unknown");
				//SetAttributeValue("Text", "Unknown");
			
			buttonInfo2.FindAdapter<Button>().Click("1;1");
			textInfo.FindAdapter<Text>().Click("1;1");
			
			Delay.Duration(500, false);
	
			buttonInfo3.FindAdapter<Button>().Click("1;1");
			
			Delay.Duration(500, false);

			// Deleted
			
			Report.Log(ReportLevel.Info, "Deleted", "Delete added element");
			buttonInfo2.FindAdapter<Button>().Click("1;1");
		}

	}
}
