///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace QQ
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Endpoint_Other_1x1 recording.
    /// </summary>
    [TestModule("178c3fe9-07ae-4f21-b48b-689b556e3ee2", ModuleType.Recording, 1)]
    public partial class Endpoint_Other_1x1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the QQRepository repository.
        /// </summary>
        public static QQRepository repo = QQRepository.Instance;

        static Endpoint_Other_1x1 instance = new Endpoint_Other_1x1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Endpoint_Other_1x1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Endpoint_Other_1x1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.GoogleChrome.Endpoint' at 63;15.", repo.NewProtocolWizard.GoogleChrome.EndpointInfo, new RecordItemIndex(0));
            repo.NewProtocolWizard.GoogleChrome.Endpoint.Click("63;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.GoogleChrome.Other' at 29;12.", repo.NewProtocolWizard.GoogleChrome.OtherInfo, new RecordItemIndex(1));
            repo.NewProtocolWizard.GoogleChrome.Other.Click("29;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.Next' at 48;10.", repo.NewProtocolWizard.NextInfo, new RecordItemIndex(2));
            repo.NewProtocolWizard.Next.Click("48;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.ListItem1x11' at 71;16.", repo.NewProtocolWizard.ListItem1x11Info, new RecordItemIndex(3));
            repo.NewProtocolWizard.ListItem1x11.Click("71;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard' at 542;433.", repo.NewProtocolWizard.SelfInfo, new RecordItemIndex(4));
            repo.NewProtocolWizard.Self.Click("542;433");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.Next' at 42;9.", repo.NewProtocolWizard.NextInfo, new RecordItemIndex(5));
            repo.NewProtocolWizard.Next.Click("42;9");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
